county_map_nba = {
          'Atlanta Hawks': 'Fulton',
          'Boston Celtics': 'Suffolk',
          'Brooklyn Nets': 'Kings',
          'Charlotte Hornets': 'Mecklenburg',
          'Chicago Bulls': 'Cook',
         'Cleveland Cavaliers': 'Cuyahoga',
          'Dallas Mavericks': 'Dallas',
          'Denver Nuggets': 'Denver',
          'Detroit Pistons': 'Wayne',
          'Golden State Warriors': 'San Francisco',
          'Houston Rockets': 'Harris',
          'Indiana Pacers': 'Marion',
          'Los Angeles Clippers': 'Los Angeles',
          'Los Angeles Lakers': 'Los Angeles',
          'Memphis Grizzlies': 'Shelby',
          'Miami Heat': 'Miami-Dade',
          'Milwaukee Bucks': 'Milwaukee', 
          'Minnesota Timberwolves': 'Hennepin',
          'New Orleans Pelicans': 'Orleans',
          'New York Knicks': 'New York',
          'Oklahoma City Thunder': 'Oklahoma',
          'Orlando Magic': 'Orange',
          'Philadelphia 76ers': 'Philadelphia',
          'Phoenix Suns': 'Maricopa',
          'Portland Trail Blazers': 'Multnomah',
          'Sacramento Kings': 'Sacramento',
          'San Antonio Spurs': 'Bexar',
          'Toronto Raptors': 'Toronto',
          'Utah Jazz': 'Salt Lake',
          'Washington Wizards': 'District of Columbia'
        }

state_map_nba = {
          'Golden State Warriors': 'California',
        'Cleveland Cavaliers': 'Ohio',
          'Portland Trail Blazers': 'Oregon',
          'Philadelphia 76ers': 'Pennsylvania',
          'Sacramento Kings': 'California',
          'Dallas Mavericks': 'Texas',
          'Utah Jazz': 'Utah',
          'Denver Nuggets': 'Colorado',
          'Charlotte Hornets': 'North Carolina',
          'Chicago Bulls': 'Illinois',
          'Washington Wizards': 'District of Columbia',
          'New York Knicks': 'New York',
          'Minnesota Timberwolves': 'Minnesota',
          'San Antonio Spurs': 'Texas',
          'Houston Rockets': 'Texas',
          'Miami Heat': 'Florida',
          'Oklahoma City Thunder': 'Oklahoma',
          'Memphis Grizzlies': 'Tennessee',
          'Los Angeles Lakers': 'California',
          'Detroit Pistons': 'Michigan',
          'Phoenix Suns': 'Arizona',
          'Milwaukee Bucks': 'Wisconsin',
          'New Orleans Pelicans': 'Louisiana',
          'Boston Celtics': 'Massachusetts',
          'Indiana Pacers': 'Indiana',
          'Brooklyn Nets': 'New York',
          'Orlando Magic': 'Florida',
          'Toronto Raptors': 'Ontario',
          'Atlanta Hawks': 'Georgia',
          'Los Angeles Clippers': 'California'
        }


state_map_wnba = {
          'New York Liberty': 'New York',
          'Minnesota Lynx': 'Minnesota',
          'Connecticut Sun': 'Connecticut',
          'Las Vegas Aces': 'Nevada',
          'Phoenix Mercury': 'Arizona',
          'Indiana Fever': 'Indiana',
          'Seattle Storm': 'Washington',
          'Atlanta Dream': 'Georgia',
          'Dallas Wings': 'Texas',
          'Los Angeles Sparks': 'California',
          'Chicago Sky': 'Illinois',
          'Washington Mystics': 'District of Columbia'
        }

county_map_wnba= {
          'Atlanta Dream': 'Fulton', 
          'Chicago Sky': 'Cook',
          'Connecticut Sun': 'New London', 
          'Dallas Wings': 'Tarrant',
          'Golden State Valkyries': 'San Francisco', 
          'Indiana Fever': 'Marion',
          'Las Vegas Aces': 'Clark',
          'Los Angeles Sparks': 'Los Angeles',
          'Minnesota Lynx': 'Hennepin',
          'New York Liberty': 'Kings',
          'Phoenix Mercury': 'Maricopa',
          'Portland Fire': 'Multnomah',
          'Seattle Storm': 'King',
          'Toronto Tempo': 'Toronto',
          'Washington Mystics': 'District of Columbia'
        }